kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Required for Ingress to expose HTTP and HTTPS
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

      # Optional: expose internal services for debugging or direct access
      - containerPort: 6379
        hostPort: 6379
        protocol: TCP
      - containerPort: 5432
        hostPort: 5432
        protocol: TCP
      - containerPort: 8083
        hostPort: 8083
        protocol: TCP
      - containerPort: 8085
        hostPort: 8085
        protocol: TCP
      - containerPort: 8084
        hostPort: 8084
        protocol: TCP
  - role: worker
