apiVersion: v1
kind: Pod
metadata:
  name: results-app-pod
  labels:
    name: results-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: results-app-pod
      image: results-service:1.0
      ports:
        - containerPort: 8085
      envFrom:
        - configMapRef:
            name: results-app-config
        - secretRef:
            name: results-app-secret
