apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app-pod
      image: "voting-service:1.0"
      ports:
        - containerPort: 8083
      envFrom:
        - configMapRef:
            name: voting-app-config