apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app-pod
      image: lukmanadeokun31/worker-service:latest
      ports:
        - containerPort: 8084
      env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "Omowunmi28"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_DB_NEW
          value: "votingdb"
        - name: REDIS_ADDR
          value: "redis:6379"